project:
  type: website

website:
  title: "Curso Cifo Daw"
  navbar:
    right:
      - text: "Home"
        href: index.qmd       
      - sidebar:apps
      - sidebar:labs
      - sidebar:albertusdylemma
      - about.qmd

  sidebar:
    - id: apps
      title: "Apps"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - linux.qmd
        - IDEs.qmd
    
    - id: labs
      title: "Labs"
      collapse-level: 3
      contents:
        - labs.qmd
        - labse02moviemanager.qmd
        - carsProject.qmd

    - id: albertusdylemma
      title: "adM"
      contents:
        - AlbertusDylemma.qmd
        - MovieManager_lab.qmd
        - key-notes_key-ideas.qmd



   
      

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



