project:
  type: website

website:
  title: "Curso Cifo Daw"
  navbar:
    right:
      - text: "Home"
        href: index.qmd       
      - sidebar:apps
      - sidebar:labs
      - about.qmd

sidebar:
  - id: apps
    title: "Apps"
    style: "docked"
    background: light
    collapse-level: 2
    contents:
      - intellij idea.qmd
      - figma.qmd
  
  - id: labs
    title: "Labs"

   
      

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



