project:
  type: website

website:
  title: "Curso Cifo Daw"
  navbar:
    right:
      - text: Home
        href: index.qmd       
      - sidebar:apps
      - labs.qmd
      - about.qmd

sidebar:
  - id: apps
    text: Apps
    title: "Apps"
    style: "docked"
    background: light
    collapse-level: 2
    contents:
      - href: apps.qmd
      - href: figma.qmd
      

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



