project:
  type: website

website:
  title: "Curso Cifo Daw"
  navbar:
    right:
      - text: "Home"
        href: home/index.qmd       
      - sidebar:apps
      - sidebar:labs
      - sidebar:albertusdylemma
      - about.qmd

  sidebar:
    - id: apps
      title: "Apps"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - apps/linux.qmd
        - apps/IDEs.qmd
    
    - id: labs
      title: "Labs"
      collapse-level: 3
      contents:
        - labs/labs.qmd
        - labs/labse02moviemanager.qmd
        - labs/carsProject.qmd

    - id: albertusdylemma
      title: "adM"
      contents:
        - adm/AlbertusDylemma.qmd
        - adm/MovieManager_lab.qmd
        - adm/key-notes_key-ideas.qmd



   
      

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



