project:
  type: website

website:
  title: "Curso Cifo Daw"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - apps.qmd
      - labs.qmd
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



